config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admins/index'
  get 'users/show'
  devise_for :admins
  devise_for :users
  # , controllers: {
  #   sessions: 'users/sessions',
  #   confirmations: 'users/confirmations',
  # registrations: 'users/registrations'
  #   passwords: 'users/passwords'
  # }
  root 'microposts#index'

  resources :users, only: %i[index show]
  resources :microposts, only: %i[new create destroy]
  resources :likes, only: %i[create destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  default_scope -> { order(created_at: :desc) }
  validates :description, presence: true
  mount_uploader :image, ImageUploader

  def like?(user)
    liked_users.include?(user)
  end

  def like(user, micropost_id)
    Like.create(user_id: user.id, micropost_id: micropost_id)
  end

  def unlike(user, micropost_id)
    Like.find_by(user_id: user.id, micropost_id: micropost_id).destroy
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :microposts, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[email name password password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @micropost.like(current_user, params[:micropost_id])
    @micropost.reload

    # respond_to do |format|
    #   format.html { redirect_to root_path }
    #   format.js
    # end
    redirect_to root_path
  end

  def destroy
    @micropost = Like.find(params[:id]).micropost
    @micropost.unlike(current_user, @micropost.id)
    @micropost.reload

    # respond_to do |format|
    #   format.html { redirect_to root_path }
    #   format.js
    # end
    redirect_to root_path
  end
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: %i[new create destroy]

  def index
    @microposts = Micropost.all
    @all_ranks = Micropost.find(Like.group(:micropost_id).order('count(micropost_id) desc').limit(4).pluck(:micropost_id)).reverse
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'Micropost successfully created'
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong'
      render 'microposts/new'
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    flash[:success] = 'Micropost deleted'
    redirect_to request.referer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:description, :image)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_admin!, only: [:index]

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.all
  end

  def index
    @users = User.all.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.slim
header.navbar.navbar-expand-md.navbar-white.bg-white
  .container
    = link_to 'TravelooT', root_path, id: "logo", class: "navbar-brand text-light text-dark"
    nav
      ul.nav
        / = render 'layouts/search'
        - if current_user.present?
          li.nav-item
            = link_to "New post", new_micropost_path, class: "nav-link"
          li.nav-item
            = link_to "My page", user_path(current_user), class: "nav-link"
          li.nav-item
            = link_to "Settings", edit_user_registration_path, class: "nav-link"
          li.nav-item
            = link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"
        - elsif current_admin.present?
          li.nav-item
            = link_to "Users", users_path, class: "nav-link"
          li.nav-item
            = link_to "Log out(admin)", destroy_admin_session_path, method: :delete, class: "nav-link"
        - else
          li.nav-item
            = link_to "Start", new_user_session_path, class: "nav-link"

app/views/layouts/_jumbotron.html.slim
/ = image_pack_tag 'journey-1130732_1920-1000-80.jpg', class: "aaa"
/ , class: "img-fluid mx-auto d-block"

.jumbotron.jumbotron-extend
    h1.site-title-sub.display-4.mt-5.text-white
        | TravelooT
    h2.site-description.mt-5.text-white
        | Introduce your favrite travel tool.

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TravelooT
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      = content_tag(:div, message, class: "flash flash_#{message_type}")
    = yield

app/views/layouts/login.html.slim
p | あああ

app/views/likes/_like.html.slim
- if micropost.like?(current_user)
    = form_with model: micropost.likes.find_by(user_id: current_user.id), method: :delete, local: true do |f|
        = button_to do
            = micropost.liked_users.count
            i.fas.fa-heart
- else
    = form_with model: micropost.likes.build, method: :post, local: true do |f|
        = hidden_field_tag :micropost_id, micropost.id
        = button_to do
            = micropost.liked_users.count
            i.far.fa-heart

app/views/likes/create.js.erb
<!-- $("#micropost-<%= @micropost.id %>.like").html("<%= j render "likes/like",
micropost: @micropost %> "); -->

<!-- $("#micropost-<%= @micropost.id %>.like").html("できてるよ") -->

<!-- $("#micropost-<%= @micropost.id %>.like").html("できてるよ") -->

app/views/likes/destroy.js.erb
<!-- $("#micropost-<%= @micropost.id %>.like").html("<%= j render "likes/like",
micropost: @micropost %> "); -->

<!-- $("#micropost-<%= @micropost.id %>.like").html("できてるよ") -->

app/views/microposts/_micropost.html.slim
/ = image_tag(product.image.url || "/app/assets/images/sample.jpg")
.card-header.d-flex.justify-content-between
    = link_to micropost.user.name, user_path(micropost.user)
    .d-inline-block
        - if current_user == micropost.user
            = link_to  "delete", micropost_path(micropost.id), method: :delete, data: { confirm: "You sure?" }
        
- if micropost.image.present?
    = image_tag micropost.image_url, class: "card-img-top"
.border-top.p-2
    p.card-text
        span id="micropost-#{micropost.id}"
            = render "likes/like", micropost: micropost
        button[data-target="#collapse-coment-#{micropost.id}" data-toggle="collapse" aria-expanded="false" type="button"]
            | read more
        div[id="collapse-coment-#{micropost.id}" class="collapse"]
            = micropost.description

app/views/microposts/index.html.slim
= render  "layouts/jumbotron"

h2.text-center
    | - Popular Post -
.card-deck
    - @all_ranks.each do |rank|
            .card.m-4
                .card-header.d-flex.justify-content-between
                    = link_to rank.user.name, user_path(rank.user)
                    .d-inline-block
                        - if current_user == rank.user
                            = link_to  "delete", micropost_path(rank.id), method: :delete, data: { confirm: "You sure?" }
                
                - if rank.image.present?
                    = image_tag rank.image_url, class: "card-img-top", height: "300"
                .border-top.p-2
                    p.card-text
                        span id="rank-#{rank.id}"
                            = render "likes/like", micropost: rank
                        button[data-target="#collapse-coment-#{rank.id}" data-toggle="collapse" aria-expanded="false" type="button"]
                            | read more
                        div[id="collapse-coment-#{rank.id}" class="collapse"]
                            = rank.description

h2.text-center.mt-5
    | - New Post -
.row
    - @microposts.each do |micropost|
        .col-sm-12.col-md-6.offset-md-3
            .card.m-3
                = render 'microposts/micropost', micropost: micropost

app/views/microposts/new.html.slim
.form.mx-auto.mt-5.container
  h2.text-center
      | New Post
  .container.mt-5
    = simple_form_for @micropost do |f|
      = f.input :image, as: :file,
                input_html: {accept: (@micropost.image.accept_extensions)},
                class: "text-center",
                label: false
      = f.input :description, class: "form-control",
                              label: false,
                              placeholder: "What's this tool?"
      .text-center.mt-3
        = f.button :submit, class: "btn btn-primary", value: "Post"

app/views/static_pages/home.html.slim
/ = image_pack_tag 'journey-1130732_1920-1000-80.jpg', class: "aaa"
/ , class: "img-fluid mx-auto d-block"

.jumbotron.jumbotron-extend
    h1.site-title-sub.display-4.mt-5
        | TravelooT
    p.site-description.mt-5
        | Introduce your favrite travel tool.

app/views/users/index.html.slim
table.table
    thead
        tr
            th[scope="col"] | ID
            th[scope="col"] | name
            th[scope="col"] | date
            / th[scope="col"] | delete
    tbody
        - @users.each do |user|
            tr
                th[scope="row"]
                    = user.id
                td
                    = link_to user.name, user_path(user)
                td
                    = user.created_at
                / td
                    = link_to "Delete", registration_path(user), data: { confirm: "Are you sure?" }, method: :delete

app/views/users/show.html.slim
h2.text-center.mt-3
    = @user.name
    |    Profile
.row
    - @microposts.each do |micropost|
        .col-sm-12.col-md-6.offset-md-3
            .card.m-3
                = render 'microposts/micropost', micropost: micropost